import Head from 'next/head'
import Image from 'next/image'
import Avatar from "../components/Avatar"
import { ViewGridIcon, MicrophoneIcon } from "@heroicons/react/solid"
import { SearchIcon } from "@heroicons/react/outline"

export default function Home() {
  return (
    <div>
      <Head>
        <title>SafeSrch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}

      <header className="flex w-full justify-between text-sm text-gray-700">
        {/* Left */}
        <div className="flex space-x-4 items-center p-4">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* Right */}
        <div className="flex space-x-4 items-center p-4">
          <p className="link">MyMail</p>
          <p className="link">Images</p>

        {/* Icon */}
        <ViewGridIcon className="h-10 transition rounded-full hover:bg-gray-100 text-gray-500 p-2" />
        
        {/* Avatar */}
          <Avatar url="https://boutiquephotographer.com/wp-content/uploads/2015/04/WORK_Headshot-Square.001_WEB.jpg"/>
        </div>
      </header>

      {/* Body */}

      <form className="flex flex-col mt-44 items-center flex-grow">
        <Image 
          src="https://cdn.vox-cdn.com/thumbor/Pkmq1nm3skO0-j693JTMd7RL0Zk=/0x0:2012x1341/1200x800/filters:focal(0x0:2012x1341)/cdn.vox-cdn.com/uploads/chorus_image/image/47070706/google2.0.0.jpg" 
          height={200} 
          width={300}
        />
      <div className="flex w-full max-w-md mt-5 hover:shadow-lg focus-within:shadow-lg rounded-full border border-gray-200 p-3 items-center sm:max-w-xl lg:max-w-2xl">
        <SearchIcon className="h-5 text-gray-500 mr-3" />
        <input type="text" className=" flex-grow focus:outline-none"/>
        <MicrophoneIcon className="h-5 text-blue-500 ml-4" />
      </div>

      <div className="mt-7 flex flex-col space-y-2 justify-center sm:flex-row sm:space-y-0 sm:space-x-4 items-center">
        <button className="btn">Google Search</button>
        <button className="btn">Surprise Me</button>
      </div>
      </form>

      {/* Footer */}      
    </div>
  )
}
